### PR TITLE
New query architecture

### LINKED ISSUE #25: Provide a way for users to cutomize `derive`s on custom types
I don't want to presuppose too much about how the generated code will be used, thus, so far, I've refrained from adding any superfluous derives to the generated types.

This might be limiting to some users wishing to add `derive`s to their types (like `Serialize` or `Clone`). I'm thinking of flags like `--custom-struct-derive`, `--custom-enum-derive` and `--custom-derive` which could be used to add the `derive` only to `struct`s, `enum`s, or both.

This will require a bit more thought though, so if you're reading this thread because you want this feature, feel free to ping me and explain how you'd like this feature to work in practice.

### PR DESCRIPTION
**Pull request by LouisGariepy**
This PR tracks the progress the new query architecture for the upcoming v0.8. This version is a significant re-architecture so there are quite a few things to do to ensure a smooth release. Some of the relevant discussions here #45, #46, and #47.

- [x] Overhaul parser
- [x] Overhaul type registration
- [x] Implement query generation
- [x] Update client code
- [x] Comment/Improve source (not perfect but its barely ok)
- [x] Update examples
- [x] Update tests
- [x] Update README

Closes #25 #39 #40 #41 #45 #46 #47 #48 #56

### CODE REVIEW

**Comment by LouisGariepy** [comment]
Composite and domain custom types don't play well with the `ToSql` and `FromSql` macro derives. I'll have to generate an impl instead of relying on the macros. I'll also need to generate an owned and borrowed version of custom types (only owned if the type is Copy).

On it! :smile_cat:

**Comment by LouisGariepy** [comment]
Also, I need to make sure arrays coming from postgres are never considered as borrowable (because `tokio_postgres` will deserialize arrays either as Vec or [T;N], not slices or iterators). This has nothing to do with Cornucopia per se, just a perfomance limitation of deserializing PostgreSQL arrays, so overall not a big deal.

**Comment by Virgiel** [comment]
I never thought about arrays :/ Unfortunately, the size of arrays in the schema is only informative but not [enforced](https://www.postgresql.org/docs/current/arrays.html). We should not use [T; N].

**Comment by Virgiel** [comment]
What if I told you we can have an iterator for arrays ?

Let start by stealing some code from `postgres-type` because they love to have everything private:

```rs
/// https://github.com/sfackler/rust-postgres/blob/38da7fa8fe0067f47b60c147ccdaa214ab5f5211/postgres-protocol/src/types/mod.rs

/// An iterator over the dimensions of an array.
pub struct ArrayDimensions<'a>(&'a [u8]);

impl<'a> FallibleIterator for ArrayDimensions<'a> {
    type Item = ArrayDimension;
    type Error = Box<dyn std::error::Error + Sync + Send>;

    #[inline]
    fn next(&mut self) -> Result<Option<ArrayDimension>, Box<dyn std::error::Error + Sync + Send>> {
        if self.0.is_empty() {
            return Ok(None);
        }

        let len = self.0.read_i32::<BigEndian>()?;
        let lower_bound = self.0.read_i32::<BigEndian>()?;

        Ok(Some(ArrayDimension { len, lower_bound }))
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        let len = self.0.len() / 8;
        (len, Some(len))
    }
}

/// Information about a dimension of an array.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ArrayDimension {
    /// The length of this dimension.
    pub len: i32,

    /// The base value used to index into this dimension.
    pub lower_bound: i32,
}

/// An iterator over the values of an array, in row-major order.
pub struct ArrayValues<'a> {
    remaining: i32,
    buf: &'a [u8],
}

impl<'a> FallibleIterator for ArrayValues<'a> {
    type Item = Option<&'a [u8]>;
    type Error = Box<dyn std::error::Error + Sync + Send>;

    #[inline]
    fn next(
        &mut self,
    ) -> Result<Option<Option<&'a [u8]>>, Box<dyn std::error::Error + Sync + Send>> {
        if self.remaining == 0 {
            if !self.buf.is_empty() {
                return Err("invalid message length: arrayvalue not drained".into());
            }
            return Ok(None);
        }
        self.remaining -= 1;

        let len = self.buf.read_i32::<BigEndian>()?;
        let val = if len < 0 {
            None
        } else {
            if self.buf.len() < len as usize {
                return Err("invalid value length".into());
            }

            let (val, buf) = self.buf.split_at(len as usize);
            self.buf = buf;
            Some(val)
        };

        Ok(Some(val))
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let len = self.remaining as usize;
        (len, Some(len))
    }
}

/// A Postgres array.
pub struct Array<'a> {
    dimensions: i32,
    has_nulls: bool,
    element_type: Oid,
    elements: i32,
    buf: &'a [u8],
}

impl<'a> Array<'a> {
    /// Returns true if there are `NULL` elements.
    #[inline]
    pub fn has_nulls(&self) -> bool {
        self.has_nulls
    }

    /// Returns the OID of the elements of the array.
    #[inline]
    pub fn element_type(&self) -> Oid {
        self.element_type
    }

    /// Returns an iterator over the dimensions of the array.
    #[inline]
    pub fn dimensions(&self) -> ArrayDimensions<'a> {
        ArrayDimensions(&self.buf[..self.dimensions as usize * 8])
    }

    /// Returns an iterator over the values of the array.
    #[inline]
    pub fn values(&self) -> ArrayValues<'a> {
        ArrayValues {
            remaining: self.elements,
            buf: &self.buf[self.dimensions as usize * 8..],
        }
    }
}
```

Now we can make our own array iterator type:
```rs
struct ArrayIterator<'a, T: FromSql<'a>> {
    values: ArrayValues<'a>,
    ty: Type,
    _type: PhantomData<T>,
}

impl<'a, T: FromSql<'a>> Iterator for ArrayIterator<'a, T> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        self.values
            .next()
            .unwrap()
            .map(|raw| T::from_sql_nullable(&self.ty, raw).unwrap())
    }
}

impl<'a, T: FromSql<'a>> FromSql<'a> for ArrayIterator<'a, T> {
    fn from_sql(
        ty: &Type,
        raw: &'a [u8],
    ) -> Result<ArrayIterator<'a, T>, Box<dyn std::error::Error + Sync + Send>> {
        let member_type = match *ty.kind() {
            Kind::Array(ref member) => member,
            _ => panic!("expected array type"),
        };

        let array = array_from_sql(raw)?;
        if array.dimensions().count()? > 1 {
            return Err("array contains too many dimensions".into());
        }

        Ok(ArrayIterator {
            ty: member_type.to_owned(),
            values: array.values(),
            _type: PhantomData::default(),
        })
    }
    
    fn accepts(ty: &postgres_types::Type) -> bool {
        match *ty.kind() {
            Kind::Array(ref inner) => T::accepts(inner),
            _ => false,
        }
    }
}
```

And taaadam:
```rs
let all = client
    .query_raw("SELECT * FROM test", std::iter::empty::<i32>())
    .await
    .unwrap();
pin_mut!(all);
while let Some(row) = all.try_next().await.unwrap() {
    let foo: ArrayIterator<&str> = row.get(0);
    let vec: Vec<_> = foo.collect();
    println!("foo: {:?}", vec);
}
```

**Comment by Virgiel** [comment]
This is just a draft (lots of unwrap and questionable to_owned) and it's a shame to have to steal so much code but how about doing something like this?

**Comment by LouisGariepy** [comment]
Wow! Thank you! I have to read the code more carefully, but it'd be a major improvement :astonished: Gonna try it out.

In a similar vein, it seems `&serde_json::Value` (notice the borrow) does not implement `FromSql`. Not sure if there's a good reason or if it's just oversight, but we might be able to solve it.

**Comment by Virgiel** [comment]
Internally `serde_json::Value` own [data](https://docs.rs/serde_json/latest/serde_json/enum.Value.html) :/
I think it is preferable for you to finish a version with always owned arrays and json, so we can make an alpha version, and then we will try to reduce allocation later until release.

**Comment by Virgiel** [comment]
We could use our custom borrowing `FromSql` and try to upstream them into `postgres`.

**Comment by LouisGariepy** [comment]
Apart from the unwraps (didn't check them carefully yet), this looks good!

> to_owned()

Don't think we can do without, but surely taking ownership of one `member_type` is better than allocating the whole array.

> Internally serde_json::Value own [data](https://docs.rs/serde_json/latest/serde_json/enum.Value.html) :/

Yeah, that's too bad :/

> I think it is preferable for you to finish a version with always owned arrays and json, so we can make an alpha version, and then we will try to reduce allocation later until release.

I'll give a single shot at your Array implementation, but I won't delay any further than that. Then I'll publish ASAP and then keep working on tests, docs, etc.

Thanks again for your contributions, as mentioned in #57 I'll soon be able to accept contributors in an official capacity.

**Comment by LouisGariepy** [comment]
> We could use our custom borrowing FromSql and try to upstream them into postgres.

Good plan.

**Comment by Virgiel** [comment]
My iterator solution has a big problem. We need a failing iterator that handles errors instead of using unwrap but the error returned is a boxed std error and we would need a `tokio-postgres::Error` to be orthogonal with the library API. But `tokio-postgres::Error` is private :/

So many things would be easier if more things were public in `postgres`, like `tokio-postgres::Error`, `slice_iter` and all the Array logic. We could ask the maintainer because I think we have a compelling use case.

**Comment by Virgiel** [comment]
One solution could be to temporarily [override](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) `tokio-postgres` with patches. I don't want to create a real fork, but just relax some internal privacy for our use.

**Comment by LouisGariepy** [comment]
Sorry I'm not totally following. Are we talking about these unwraps?

```rust
impl<'a, T: FromSql<'a>> Iterator for ArrayIterator<'a, T> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        self.values
            .next()
            .unwrap() //<-- this
            .map(|raw| T::from_sql_nullable(&self.ty, raw).unwrap()) <-- that
    }
}
```

**Comment by Virgiel** [comment]
Both

**Comment by LouisGariepy** [comment]
@Virgiel Yeah that's what I was assuming too. If this is the case, it fine by me to panic/unwrap.

**Comment by Virgiel** [comment]
> In a similar vein, it seems `&serde_json::Value` (notice the borrow) does not implement `FromSql`. Not sure if there's a good reason or if it's just oversight, but we might be able to solve it.

What about [RawValue](https://docs.rs/serde_json/latest/serde_json/value/struct.RawValue.html) ? Should do the trick !

**Comment by LouisGariepy** [comment]
> > In a similar vein, it seems `&serde_json::Value` (notice the borrow) does not implement `FromSql`. Not sure if there's a good reason or if it's just oversight, but we might be able to solve it.
> 
> What about [RawValue](https://docs.rs/serde_json/latest/serde_json/value/struct.RawValue.html) ? Should do the trick !

Something like this? 
```rust

struct JsonBorrowed<'a>(&'a RawValue);

impl<'a> FromSql<'a> for JsonBorrowed<'a> {
    fn from_sql(
        ty: &Type,
        mut raw: &'a [u8],
    ) -> Result<JsonBorrowed<'a>, Box<dyn std::error::Error + Sync + Send>> {
        if *ty == Type::JSONB {
            let mut b = [0; 1];
            raw.read_exact(&mut b)?;
            // We only support version 1 of the jsonb binary format
            if b[0] != 1 {
                return Err("unsupported JSONB encoding version".into());
            }
        }
        serde_json::de::from_slice(raw)
            .map(JsonBorrowed)
            .map_err(Into::into)
    }

    accepts!(JSON, JSONB);
}

```

**Comment by LouisGariepy** [comment]
> Erratum
> Array logic is public in postgres-protocol

:open_mouth:

**Comment by Virgiel** [comment]
> Something like this?

There is already a [type](https://docs.rs/tokio-postgres/latest/tokio_postgres/types/struct.Json.html) for `Deserialize` from `tokio-prostgres`:
```rs
 let json: tokio_postgres::types::Json<&RawValue> = row.get(0);
```

**Comment by Virgiel** [comment]
> Something like this?

There is already a [type](https://docs.rs/tokio-postgres/latest/tokio_postgres/types/struct.Json.html) for `Deserialize` from `tokio-postgres`:
```rs
 let json: tokio_postgres::types::Json<&RawValue> = row.get(0);
```

**Comment by LouisGariepy** [comment]
Alright, the code generate works, at least to generate queries for the code we already had.

I have to stress that the code is pretty unsightly (understatement), but it is there and it does seem to work. Tomorrow I'll be able to clean up the code and check the other items for this PR. Cheers!

**Comment by LouisGariepy** [comment]
(Tests are disabled right now, which is why the CI marks them as passing)

**Comment by LouisGariepy** [comment]
Still a bit of an issue with borrowing wrapper types, but I know how to solve it I think. A lot of progress has been made though.

**Comment by LouisGariepy** [comment]
I think codegen is good to go now (albeit, as I said above, in a very unruly form). Will try to wire some tests tonight...

**Comment by Virgiel** [comment]
Sorry for the last minute proposal today, I hope I didn't waste too much of your time. Thanks for your hard work on this rewrite!

**Comment by LouisGariepy** [comment]
There's this weird interaction in `tokio_postgres` which results in PostgreSql domains sometimes being interpreted as the proper Rust newtype, but also sometimes as the inner type. This seems to happen only in return columns, but I'm not sure. It's not a bug either, the behaviour is fine, it's just a little unexpected.

In any case this is pretty niche and harmless, and it's not something we can fix within cornucopia. Eventually, I could try to reach out to `tokio_postgres` to better understand what's up.

For now, I won't block further on this since I don't consider it to be a bug within Cornucopia.

**Comment by LouisGariepy** [comment]
I messed up the implementation of `FromSql` for borrowed custom types, but that should be pretty easy to fix, and appart from that, all tests pass :partying_face:

**Comment by Virgiel** [comment]
> There's this weird interaction in `tokio_postgres` which results in PostgreSql domains sometimes being interpreted as the proper Rust newtype, but also sometimes as the inner type. This seems to happen only in return columns, parameters are inferred correctly. It doesn't cause errors within Cornucopia, the behaviour is fine, it's just a little unexpected. Worst case scenario the user has to map this one field to wrap it in their newtype. Not ideal, but in the end it is pretty niche and harmless.

I couldn't find an explicit specification in the PostgreSQL documentation, but it seems from the questions and answers on the Internet that this is the correct behavior.
The [documentation](https://www.postgresql.org/docs/current/domains.html) states that "When an operator or function of the underlying type is applied to a domain value, the domain is automatically down-cast to the underlying type." This may be what happens on return. 
 So no problem with that

**Comment by Virgiel** [comment]
After you push these changes I will be interested in writing a more complex test suite, especially one that tests we detect errors and show a well-formatted error message

**Comment by LouisGariepy** [comment]
> I messed up the implementation of `FromSql` for borrowed custom types

Fixed!

**Comment by LouisGariepy** [comment]
I just realized I forgot to handle nullable columns. Should be quick.

**Comment by LouisGariepy** [comment]
Now passes CI :rocket:

**Comment by LouisGariepy** [comment]
Unless I missed something, the only remaining tasks are doc-related.

**Comment by Virgiel** [comment]
While trying to torture the codegen I found that nullable and array do not work well together:

```sql
-- Write your migration SQL here
CREATE TYPE nightmare_composite AS (
    custom custom_composite[],
    spongebob spongebob_character[]
);

CREATE TABLE nightmare (
    composite nightmare_composite NOT NULL,
    name TEXT NOT NULL,
    names TEXT[] NOT NULL,
    data BYTEA,
    datas BYTEA[]
);

INSERT INTO nightmare (composite, name, names)
    VALUES (
        ROW(
            CAST (ARRAY[ROW('incredible', 42, 'Patrick')] as custom_composite[]),
            CAST (ARRAY['Bob', 'Patrick'] as spongebob_character[])
            ), 
        'Bob', 
        ARRAY['I', 'Love', 'Chocolate']
    );
```

```sql
--! nightmare ?{data, datas}
SELECT * FROM nightmare;
```

**Comment by Virgiel** [comment]
We also need a way to specify if items in arrays or columns in composite types are nullable, but this is not blocking this PR.

**Comment by Virgiel** [comment]
If codegen is no longer having nightmares, I think it's ready for a merge

**Pull request merged**
